const USERS = [
  {
    id: '1',
    matricule: 'M001',
    firstname: 'GuyHawkins',
    lastname: 'Codylastnamer',
    birth_date: '24/2020',
    post: { name: 'teste', department: { name: 'Production' } },
  },
  {
    id: '2',
    matricule: 'M002',
    firstname: 'GuyHawkins',
    lastname: 'Cody Fisher',
    birth_date: '24/03/2020',
    post: { name: 'teste', department: { name: 'Production' } },
  },
  {
    id: '3',
    matricule: 'M003',
    firstname: 'GuyHawkins',
    lastname: 'Cody Fisher',
    birth_date: '24/03/2020',
    post: { name: 'teste', department: { name: 'Production' } },
  },
  {
    id: '4',
    matricule: 'M004',
    firstname: 'GuyHawkins',
    lastname: 'Cody Fisher',
    birth_date: '24/03/2020',
    post: { name: 'teste', department: { name: 'Production' } },
  },
  {
    id: '5',
    matricule: 'M005',
    firstname: 'GuyHawkins',
    lastname: 'Cody Fisher',
    birth_date: '24/03/2020',
    post: { name: 'teste', department: { name: 'Production' } },
  },
  {
    id: '6',
    matricule: 'M006',
    firstname: 'GuyHawkins',
    lastname: 'Cody Fisher',
    birth_date: '24/03/2020',
    post: { name: 'teste', department: { name: 'Production' } },
  },
  {
    id: '7',
    matricule: 'M007',
    firstname: 'GuyHawkins',
    lastname: 'Cody Fisher',
    birth_date: '24/03/2020',
    post: { name: 'teste', department: { name: 'Production' } },
  },
  {
    id: '8',
    matricule: 'M008',
    firstname: 'GuyHawkins',
    lastname: 'Cody Fisher',
    birth_date: '24/03/2020',
    post: { name: 'teste', department: { name: 'Production' } },
  },
  {
    id: '9',
    matricule: 'M009',
    firstname: 'GuyHawkins',
    lastname: 'Cody Fisher',
    birth_date: '24/03/2020',
    post: { name: 'teste', department: { name: 'Production' } },
  },
  {
    id: '10',
    matricule: 'M010',
    firstname: 'GuyHawkins',
    lastname: 'Cody Fisher',
    birth_date: '24/03/2020',
    post: { name: 'teste', department: { name: 'Production' } },
  },
  {
    id: '11',
    matricule: 'M011',
    firstname: 'GuyHawkins',
    lastname: 'Cody Fisher',
    birth_date: '24/03/2020',
    post: { name: 'teste', department: { name: 'Production' } },
  },
  {
    id: '12',
    matricule: 'M012',
    firstname: 'GuyHawkins',
    lastname: 'Cody Fisher',
    birth_date: '24/03/2020',
    post: { name: 'teste', department: { name: 'Production' } },
  },
];

export default USERS;
