version: '3.3'

services:
  postgres:
    image: postgres:16.2
    restart: unless-stopped
    ports:
      - '${DATABASE_PORT}:5432'
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
